In [1]:
#P53: Método apply()
import pandas as pd

In [2]:
#1 Importa as bases de dados
flags = pd.read_csv('/Users/TullioPires/flags.csv')

In [3]:
#2 Apply
flags['name'] = flags['name'].apply(str.upper)

In [4]:
#3 Imprime o DataFrame ALT
flags

,name,landmass,zone,area,population,language,religion,bars,stripes,colours,...,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
0,AFGHANISTAN,5,1,648,16,10,2,0,3,5,...,0,0,1,0,0,1,0,0,black,green
1,ALBANIA,3,1,29,3,6,6,0,0,3,...,0,0,1,0,0,0,1,0,red,red
2,ALGERIA,4,1,2388,20,8,2,2,0,3,...,0,0,1,1,0,0,0,0,green,white
3,AMERICAN-SAMOA,6,3,0,0,1,1,0,0,5,...,0,0,0,0,1,1,1,0,blue,red
4,ANDORRA,3,1,0,0,6,0,3,0,3,...,0,0,0,0,0,0,0,0,blue,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,WESTERN-SAMOA,6,3,3,0,1,1,0,0,3,...,0,1,5,0,0,0,0,0,blue,red
190,YUGOSLAVIA,3,1,256,22,6,6,0,3,4,...,0,0,1,0,0,0,0,0,blue,red
191,ZAIRE,4,2,905,28,10,5,0,0,4,...,0,0,0,0,0,1,1,0,green,green
192,ZAMBIA,4,2,753,6,10,5,3,0,4,...,0,0,0,0,0,0,1,0,green,brown
193,ZIMBABWE,4,2,391,8,10,5,0,7,5,...,0,0,1,0,1,1,1,0,green,green